server:
  port: 8002
spring:
  application:
    name: eurekaserver01
eureka:
  client:
    service-url:
      defaultZone: http://192.168.197.1:8002/eureka/,http://192.168.197.1:8001/eureka/
    fetch-registry: true
    register-with-eureka: false
