server:
  port: 8001
spring:
  application:
    name: eurekaserver01
eureka:
  instance:
    hostname: 192.168.187.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname}:8002/eureka/
    fetch-registry: true
    register-with-eureka: false

