spring:

  application:
    name: classprovider
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样取值介于 0到1之间，1则表示全部收集
        probability: 1

  datasource:
    url: jdbc:mysql://192.168.187.1:3306/shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8006
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.187.1:8001/eureka,http://192.168.187.1:8002/eureka
